language: java

jdk:
  - oraclejdk8
  - oraclejdk7
# TODO - use openjdk7 again when this travis issue is handled
#      - https://github.com/travis-ci/travis-ci/issues/5227
#  - openjdk7

after_success:
  - mvn clean test jacoco:report coveralls:report
  - curl http://www.jpm4j.org/install/script > jpmInstall.sh
  - sudo sh jpmInstall.sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
  - codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
